name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  sqflite: any
  path_provider: 
  file_picker: ^1.4.3+2 
  http:
  firebase_messaging: ^4.0.0+1
  cloud_firestore: ^0.13.0+1
  fluttertoast: ^3.1.0
  flutter_local_notifications: ^0.7.1+1 
  firebase_storage:
    git:
      url: git://github.com/danysz/flutterfire.git
      ref: master
      path: packages/firebase_storage
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
